name = 'Sleeve'
license = 'MIT'
licenselink = 'https://github.com/mmatokovic/sleeve/blob/main/LICENSE'
description = 'Sleeve is a minimalist and responsive theme for Hugo designed to create fast, clean, and aesthetically pleasing websites.'

homepage = 'https://github.com/mmatokovic/sleeve'

demosite = 'https://mmatokovic.github.io/sleeve'

tags = ['blog', 'tailwindcss', 'responsive', 'multilingual', 'dark', 'personal']
features = ['responsive', 'dark mode', 'json-ld']

[author]
  name = 'Mislav Matokovic'
  homepage = 'https://mmatokovic.dev'